AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-hls-mp4-converter

Parameters:
  
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: Dev

  IVSBucketName:
    Description: IVS Recording Bucket Name
    Type: String

Resources:
  FFmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/ffmpeg
      CompatibleRuntimes:
        - python3.8
        - python3.7
        - python3.6

  StreamConvertFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/stream_converter/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 2048
      Timeout: 900
      Tracing: Active
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref IVSBucketName
        - S3WritePolicy:
            BucketName: !Ref IVSBucketName
      Layers:
        - !Ref FFmpegLayer
      Events:
        Trigger:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.ivs
              detail-type:
                - IVS Recording State Change
              detail:
                recording_status:
                  - Recording End

Outputs:
  StreamConvertFunction:
    Description: "StreamConvert Lambda Function ARN"
    Value: !GetAtt StreamConvertFunction.Arn

